import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
import SupabaseProvider from "./supabase-provider";

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   //  const event = await getEvent();
   //  console.log(event);
   return (
      <html lang="en">
         <body>
            {/* <SupabaseProvider session={session}> */}
            {/* <SupabaseListener serverAccessToken={session?.access_token} /> */}
            {children}
            {/* </SupabaseProvider> */}
         </body>
      </html>
   );
}
